---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: pacman-dr
  namespace: pacman-dr
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - pacman-dr
...
