---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-bgd-eks
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - clusterDecisionResource:
              configMapRef: acm-placement
              labelSelector:
                matchLabels:
                  cluster.open-cluster-management.io/placement: app-gitops-placement-eks
              requeueAfterSeconds: 180
          - list:
              elements:
                - env: dev-eks
                - env: pre-eks
                - env: pro-eks
  template:
    metadata:
      name: "app-bgd-{{ name }}-{{ env }}"
    spec:
      ignoreDifferences:
        - kind: ServiceAccount
          jsonPointers:
            - /imagePullSecrets
            - /secrets
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
      source:
        repoURL: "https://github.com/silvinux/bgd-acm-gitops.git"
        targetRevision: "main"
        path: "applications/bgd/overlays/{{ env }}"
      destination:
        namespace: "{{ env }}-bgd"
        server: "{{ server }}"
...
