kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: guestbook-rolebinding
subjects:
  - kind: ServiceAccount
    name: guestbook-sa
roleRef:
  kind: Role
  name: guestbook-role
  apiGroup: rbac.authorization.k8s.io
