---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-eks-
resources:
  - ../../base-eks
  - namespace.yaml
  - secret.yaml
  - sa.yaml
patches:
  - path: deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: bgd
      labelSelector: "app=bgd"
commonLabels:
  env: dev-eks-bgd
...
