---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base-common
  - ../../base-ocp
  - namespace.yaml
  - secret.yaml
  - sa.yaml
patches:
  - path: deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: bgd
      labelSelector: "app=bgd"

commonLabels:
  env: pre-ocp-bgd
...
